import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Dollar ERP: ERP Software for Retailers, Distributors, and Manufacturers » Feed"
          href="https://dollarerp.com/feed/"
        />
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Dollar ERP: ERP Software for Retailers, Distributors, and Manufacturers » Comments Feed"
          href="https://dollarerp.com/comments/feed/"
        />
        <link
          rel="stylesheet"
          id="pa-frontend-css"
          href="https://dollarerp.com/wp-content/uploads/premium-addons-elementor/pa-frontend-a285291b3.min.css?ver=1732532447"
          media="all"
        />
        <style
          id="wp-emoji-styles-inline-css"
          dangerouslySetInnerHTML={{
            __html:
              "\n\n\timg.wp-smiley, img.emoji {\n\t\tdisplay: inline !important;\n\t\tborder: none !important;\n\t\tbox-shadow: none !important;\n\t\theight: 1em !important;\n\t\twidth: 1em !important;\n\t\tmargin: 0 0.07em !important;\n\t\tvertical-align: -0.1em !important;\n\t\tbackground: none !important;\n\t\tpadding: 0 !important;\n\t}\n",
          }}
        />
        <style
          id="rank-math-toc-block-style-inline-css"
          dangerouslySetInnerHTML={{
            __html:
              '\n.wp-block-rank-math-toc-block nav ol{counter-reset:item}.wp-block-rank-math-toc-block nav ol li{display:block}.wp-block-rank-math-toc-block nav ol li:before{content:counters(item, ".") ". ";counter-increment:item}\n\n',
          }}
        />
        <link
          rel="stylesheet"
          id="nta-css-popup-css"
          href="https://dollarerp.com/wp-content/plugins/wp-whatsapp/assets/dist/css/style.css?ver=6.7.1"
          media="all"
        />
        <style
          id="classic-theme-styles-inline-css"
          dangerouslySetInnerHTML={{
            __html:
              "\n/*! This file is auto-generated */\n.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}\n",
          }}
        />
        <style
          id="global-styles-inline-css"
          dangerouslySetInnerHTML={{
            __html:
              "\n:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);}:where(.is-layout-flex){gap: 0.5em;}:where(.is-layout-grid){gap: 0.5em;}body .is-layout-flex{display: flex;}.is-layout-flex{flex-wrap: wrap;align-items: center;}.is-layout-flex > :is(*, div){margin: 0;}body .is-layout-grid{display: grid;}.is-layout-grid > :is(*, div){margin: 0;}:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}\n:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}\n:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}\n:root :where(.wp-block-pullquote){font-size: 1.5em;line-height: 1.6;}\n",
          }}
        />
        <>
          <link
            rel="stylesheet"
            id="hello-elementor-css"
            href="https://dollarerp.com/wp-content/themes/hello-elementor/style.min.css?ver=3.0.1"
            media="all"
          />
          <link
            rel="stylesheet"
            id="hello-elementor-theme-style-css"
            href="https://dollarerp.com/wp-content/themes/hello-elementor/theme.min.css?ver=3.0.1"
            media="all"
          />
          <link
            rel="stylesheet"
            id="hello-elementor-header-footer-css"
            href="https://dollarerp.com/wp-content/themes/hello-elementor/header-footer.min.css?ver=3.0.1"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-frontend-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/frontend.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-post-31-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/post-31.css?ver=1729190223"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-icons-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css?ver=5.31.0"
            media="all"
          />
          <link
            rel="stylesheet"
            id="swiper-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css?ver=8.4.5"
            media="all"
          />
          <link
            rel="stylesheet"
            id="e-swiper-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/conditionals/e-swiper.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-pro-css"
            href="https://dollarerp.com/wp-content/plugins/pro-elements/assets/css/frontend.min.css?ver=3.20.2"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-global-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/global.css?ver=1729190223"
            media="all"
          />
          <link
            rel="stylesheet"
            id="widget-image-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/widget-image.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="e-animations-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/animations/animations.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="widget-text-editor-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/widget-text-editor.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="widget-heading-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/widget-heading.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="widget-icon-box-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/widget-icon-box.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="font-awesome-5-all-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/all.min.css?ver=4.10.28"
            media="all"
          />
          <link
            rel="stylesheet"
            id="pa-slick-css"
            href="https://dollarerp.com/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-css/slick.min.css?ver=4.10.28"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-post-402-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/post-402.css?ver=1729191423"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-post-129-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/post-129.css?ver=1729190223"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-post-2330-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/post-2330.css?ver=1729190224"
            media="all"
          />
          <link
            rel="stylesheet"
            id="tablepress-default-css"
            href="https://dollarerp.com/wp-content/plugins/tablepress/css/build/default.css?ver=2.3"
            media="all"
          />
          <link
            rel="stylesheet"
            id="eael-general-css"
            href="https://dollarerp.com/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/css/view/general.min.css?ver=5.9.15"
            media="all"
          />
          <link
            rel="stylesheet"
            id="sib-front-css-css"
            href="https://dollarerp.com/wp-content/plugins/mailin/css/mailin-front.css?ver=6.7.1"
            media="all"
          />
          <link
            rel="stylesheet"
            id="google-fonts-1-css"
            href="https://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto+Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CPoppins%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto+Condensed%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&display=swap&ver=6.7.1"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-icons-shared-0-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.3"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-icons-fa-solid-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min.css?ver=5.15.3"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-icons-fa-brands-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/font-awesome/css/brands.min.css?ver=5.15.3"
            media="all"
          />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com/"
            crossOrigin=""
          />
          <link
            rel="https://api.w.org/"
            href="https://dollarerp.com/wp-json/"
          />
          <link
            rel="alternate"
            title="JSON"
            type="application/json"
            href="https://dollarerp.com/wp-json/wp/v2/pages/402"
          />
          <link
            rel="EditURI"
            type="application/rsd+xml"
            title="RSD"
            href="https://dollarerp.com/xmlrpc.php?rsd"
          />
          <meta name="generator" content="WordPress 6.7.1" />
          <link rel="shortlink" href="https://dollarerp.com/" />
          <link
            rel="alternate"
            title="oEmbed (JSON)"
            type="application/json+oembed"
            href="https://dollarerp.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fdollarerp.com%2F"
          />
          <link
            rel="alternate"
            title="oEmbed (XML)"
            type="text/xml+oembed"
            href="https://dollarerp.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fdollarerp.com%2F&format=xml"
          />
          <meta
            name="generator"
            content="Elementor 3.24.7; features: additional_custom_breakpoints; settings: css_print_method-external, google_font-enabled, font_display-swap"
          />
          <style
            dangerouslySetInnerHTML={{
              __html:
                "\n\t\t\t\t.e-con.e-parent:nth-of-type(n+4):not(.e-lazyloaded):not(.e-no-lazyload),\n\t\t\t\t.e-con.e-parent:nth-of-type(n+4):not(.e-lazyloaded):not(.e-no-lazyload) * {\n\t\t\t\t\tbackground-image: none !important;\n\t\t\t\t}\n\t\t\t\t@media screen and (max-height: 1024px) {\n\t\t\t\t\t.e-con.e-parent:nth-of-type(n+3):not(.e-lazyloaded):not(.e-no-lazyload),\n\t\t\t\t\t.e-con.e-parent:nth-of-type(n+3):not(.e-lazyloaded):not(.e-no-lazyload) * {\n\t\t\t\t\t\tbackground-image: none !important;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\t@media screen and (max-height: 640px) {\n\t\t\t\t\t.e-con.e-parent:nth-of-type(n+2):not(.e-lazyloaded):not(.e-no-lazyload),\n\t\t\t\t\t.e-con.e-parent:nth-of-type(n+2):not(.e-lazyloaded):not(.e-no-lazyload) * {\n\t\t\t\t\t\tbackground-image: none !important;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t",
            }}
          />
          <link
            rel="icon"
            href="https://dollarerp.com/wp-content/uploads/2023/05/Dollarerp-150x150.ico"
            sizes="32x32"
          />
          <link
            rel="icon"
            href="https://dollarerp.com/wp-content/uploads/2023/05/Dollarerp.ico"
            sizes="192x192"
          />
          <link
            rel="apple-touch-icon"
            href="https://dollarerp.com/wp-content/uploads/2023/05/Dollarerp.ico"
          />
          <meta
            name="msapplication-TileImage"
            content="https://dollarerp.com/wp-content/uploads/2023/05/Dollarerp.ico"
          />
          <style
            id="wpforms-css-vars-root"
            dangerouslySetInnerHTML={{
              __html:
                "\n\t\t\t\t:root {\n\t\t\t\t\t--wpforms-field-border-radius: 3px;\n--wpforms-field-background-color: #ffffff;\n--wpforms-field-border-color: rgba( 0, 0, 0, 0.25 );\n--wpforms-field-text-color: rgba( 0, 0, 0, 0.7 );\n--wpforms-label-color: rgba( 0, 0, 0, 0.85 );\n--wpforms-label-sublabel-color: rgba( 0, 0, 0, 0.55 );\n--wpforms-label-error-color: #d63637;\n--wpforms-button-border-radius: 3px;\n--wpforms-button-background-color: #066aab;\n--wpforms-button-text-color: #ffffff;\n--wpforms-field-size-input-height: 43px;\n--wpforms-field-size-input-spacing: 15px;\n--wpforms-field-size-font-size: 16px;\n--wpforms-field-size-line-height: 19px;\n--wpforms-field-size-padding-h: 14px;\n--wpforms-field-size-checkbox-size: 16px;\n--wpforms-field-size-sublabel-spacing: 5px;\n--wpforms-field-size-icon-size: 1;\n--wpforms-label-size-font-size: 16px;\n--wpforms-label-size-line-height: 19px;\n--wpforms-label-size-sublabel-font-size: 14px;\n--wpforms-label-size-sublabel-line-height: 17px;\n--wpforms-button-size-font-size: 17px;\n--wpforms-button-size-height: 41px;\n--wpforms-button-size-padding-h: 15px;\n--wpforms-button-size-margin-top: 10px;\n\n\t\t\t\t}\n\t\t\t",
            }}
          />
          {/* Google tag (gtag.js) */}
        </>
        <>
          <link
            rel="stylesheet"
            id="widget-social-icons-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/widget-social-icons.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="e-apple-webkit-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/css/conditionals/apple-webkit.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="elementor-post-1989-css"
            href="https://dollarerp.com/wp-content/uploads/elementor/css/post-1989.css?ver=1729190170"
            media="all"
          />
          <link
            rel="stylesheet"
            id="e-animation-slideInLeft-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/animations/styles/slideInLeft.min.css?ver=3.24.7"
            media="all"
          />
          <link
            rel="stylesheet"
            id="e-animation-slideInRight-css"
            href="https://dollarerp.com/wp-content/plugins/elementor/assets/lib/animations/styles/slideInRight.min.css?ver=3.24.7"
            media="all"
          />
        </>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
